default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: 192.168.99.100 # `docker-machine ip default`
  port: 5432
  pool: 5
  username: postgres
  password: mysecretpassword

development:
  <<: *default
  database: boscaiola_development

test:
  <<: *default
  database: boscaiola_test

production:
  adapter:
  host:
  port:
  encoding:
  database:
  username:
  password:
  pool: 5
  timeout: 5000

